---
version: "2.0"
endpoints:
  router:
    kind: ip

services:
  bee:
    image: ethersphere/bee:2.6.0
    expose:
      - port: 1633
        as: 1633
        to:
          - global: false
          - service: varnish
      - port: 1634
        as: 1634
        to:
          - global: false
          - service: varnish
    env:
      - BEE_API_ADDR=:1633
      - BEE_FULL_NODE=false
      - BEE_SWAP_ENABLE=false
      - BEE_BLOCKCHAIN_RPC_ENDPOINT=https://gnosis.oat.farm
      - BEE_CORS_ALLOWED_ORIGINS=*
    command:
      - bee
    args:
      - start

  caddy:
    image: ghcr.io/o8is/swarm-router-caddy:latest
    expose:
      - port: 80
        as: 80
        to:
          - global: true
            ip: router
      - port: 443
        as: 443
        to:
          - global: true
            ip: router
    command:
      - caddy
    args:
      - run
      - --config
      - /etc/caddy/Caddyfile

  varnish:
    image: octalmage/swarm-varnish:0.1.5
    expose:
      - port: 8080
        as: 8080
        to:
          - global: false
          - service: caddy
      - port: 6081
        as: 6081
        to:
          - global: false
    env:
      - VARNISH_SIZE=256M
    command:
      - varnishd
    args:
      - -F
      - -a
      - :8080
      - -f
      - /etc/varnish/default.vcl
      - -s
      - malloc,256M

  gatekeeper:
    image: ghcr.io/o8is/swarm-router-gatekeeper:latest
    expose:
      - port: 9123
        as: 9123
        to:
          - global: false
          - service: caddy
    env:
      - PORT=9123

profiles:
  compute:
    bee:
      resources:
        cpu:
          units: 2
        memory:
          size: 2Gi
        storage:
          - size: 2Gi
    caddy:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 1Gi
    varnish:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 500Mi
    gatekeeper:
      resources:
        cpu:
          units: 1
        memory:
          size: 512Mi
        storage:
          - size: 512Mi

  placement:
    dc1:
      pricing:
        bee:
          denom: uakt
          amount: 10000
        caddy:
          denom: uakt
          amount: 10000
        varnish:
          denom: uakt
          amount: 10000
        gatekeeper:
          denom: uakt
          amount: 10000
      attributes:
        host: akash

deployment:
  bee:
    dc1:
      profile: bee
      count: 1
  caddy:
    dc1:
      profile: caddy
      count: 1
  varnish:
    dc1:
      profile: varnish
      count: 1
  gatekeeper:
    dc1:
      profile: gatekeeper
      count: 1